# -*- coding: utf-8 -*-
"""practica_experi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rqp9BYdmttGgbJNujTxOndKTYmDUBpSZ

##ALGORITMO DIJKSTRA
"""

import heapq

def dijkstra(grafo, inicio):
    # Distancias iniciales: infinito para todos menos el nodo de inicio
    distancias = {nodo: float('inf') for nodo in grafo}
    distancias[inicio] = 0

    # Cola de prioridad para elegir el nodo más cercano
    cola_prioridad = [(0, inicio)]

    while cola_prioridad:
        distancia_actual, nodo_actual = heapq.heappop(cola_prioridad)

        # Si encontramos una distancia mayor, no es óptima y la ignoramos
        if distancia_actual > distancias[nodo_actual]:
            continue

        # Explorar vecinos
        for vecino, peso in grafo[nodo_actual].items():
            distancia = distancia_actual + peso

            # Si encontramos una ruta más corta, actualizamos
            if distancia < distancias[vecino]:
                distancias[vecino] = distancia
                heapq.heappush(cola_prioridad, (distancia, vecino))

    return distancias

grafo = {
    'A': {'B': 2, 'C': 5},
    'B': {'A': 2, 'C': 6, 'D': 1},
    'C': {'A': 5, 'B': 6, 'D': 2, 'E': 5},
    'D': {'B': 1, 'C': 2, 'E': 1},
    'E': {'C': 5, 'D': 1}
}

resultado = dijkstra(grafo, 'A')
print("Distancias mínimas desde A:")
for nodo, distancia in resultado.items():
    print(f"A → {nodo}: {distancia}")

"""##Algoritmo de Floyd-Warshall

"""

def floyd_warshall(grafo):
    # Número de nodos
    nodos = list(grafo.keys())
    n = len(nodos)

    # Inicializar matriz de distancias
    dist = [[float('inf')] * n for _ in range(n)]

    # Distancia a sí mismo = 0
    for i in range(n):
        dist[i][i] = 0

    # Llenar con valores del grafo
    for u in grafo:
        for v, peso in grafo[u].items():
            dist[nodos.index(u)][nodos.index(v)] = peso

    # Algoritmo principal
    for k in range(n):
        for i in range(n):
            for j in range(n):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]

    # Mostrar resultado
    print("Matriz de distancias mínimas:")
    for fila in dist:
        print(fila)

# Grafo de ejemplo
grafo = {
    'A': {'B': 3, 'C': 8},
    'B': {'C': 2, 'D': 5},
    'C': {'D': 1},
    'D': {'A': 2}
}

floyd_warshall(grafo)

"""##Búsqueda en Anchura (BFS)"""

from collections import deque

def bfs(grafo, inicio, meta):
    visitados = set()
    cola = deque([[inicio]])
    while cola:
        camino = cola.popleft() # Corrected indentation
        nodo = camino[-1]       # Corrected indentation
        if nodo == meta:
            return camino
        # This block was previously incorrectly indented, making it unreachable or misplaced.
        # It should be at the same indentation level as 'if nodo == meta:'.
        if nodo not in visitados:
            visitados.add(nodo) # Mark node as visited when it's being processed
            for vecino in grafo[nodo]:
                # Only add neighbor to queue if it hasn't been visited yet to avoid cycles and redundant paths
                if vecino not in visitados:
                    nuevo_camino = list(camino)
                    nuevo_camino.append(vecino)
                    cola.append(nuevo_camino)
    return None # This should be outside the while loop if no path is found

# Grafo de ejemplo
grafo = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

print("Camino BFS de A a F:", bfs(grafo, 'A', 'F'))